version: "3.8"

services:
  liveness-service:
    build:
      context: .
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - liveness-network

networks:
  liveness-network:
    driver: bridge
