# Base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY liveness-service/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY liveness-service/ .

# Expose the port the service runs on
EXPOSE 3002

# Start the application
CMD ["npm", "start"]
