version: "3.8"

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8757:8757"
    environment:
      - PORT=8757
      - AUTH_SERVICE_URL=http://auth-service:3001
      - LIVENESS_SERVICE_URL=http://liveness-service:3002
    depends_on:
      - auth-service
      - liveness-service

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  liveness-service:
    build:
      context: .
      dockerfile: liveness-service/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
