version: "3.8"

services:
  auth-service:
    build:
      context: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - liveness-network

networks:
  liveness-network:
    driver: bridge
