# Base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the .env file
COPY .env /app/.env

# Copy the rest of the application
COPY . .

# Expose the port the service runs on
EXPOSE 3001

# Start the application
CMD ["npm", "start"]
